spec:
  destination:
    server: <PROD_CLUSTER_ENDPOINT> # Replace after Terraform creates the cluster
  source:
    repoURL: <GITLAB_REPO_URL>
    targetRevision: main

backend: {}
frontend: {}
externalSecrets: {}
externalDns: {}
kubePrometheusStack: {}
loki: {}
alloy: {}
postgresExporter: {}