spec:
  destination:
    server: https://<prod-cluster-api-endpoint>
  source:
    repoURL: <your-gitlab-repo>
    targetRevision: main

backend: {}
frontend: {}
externalSecrets: {}
externalDns: {}
kubePrometheusStack: {}
loki: {}
alloy: {}
postgresExporter: {}