externalDns:
  chartVersion: "1.16.1"
  values:
    provider:
      name: google
    extraArgs:
      - --google-project=voyager-prod-500708
      - --google-zone-visibility=public
    domainFilters:
      - prod-public.kood-voyager.com
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-dns@voyager-prod-500708.iam.gserviceaccount.com
    nodeSelector:
      role: tools
    tolerations:
      - key: role
        value: tools
        effect: NoSchedule