spec:
  destination:
    server: https://<prod-cluster-api-endpoint> # Replace after Terraform ceates the cluster
  source:
    repoURL: https://gitlab.com/devops_daddy/cloud-migration-gcp.git
    targetRevision: main

backend: {}
frontend: {}
externalSecrets: {}
externalDns: {}
kubePrometheusStack: {}
loki: {}
alloy: {}
postgresExporter: {}