frontend:
  image:
      repository: <GCP_REGION>-docker.pkg.dev/<SHARED_PROJECT_ID>/voyager/frontend
  backendUrl: "http://prod-backend-backend:8080"
  apiUrl: ""
  ingress:
    enabled: true
    host: frontend.prod-public.<DOMAIN>
    additionalHosts:
      - www.<DOMAIN>
    annotations:
      networking.gke.io/managed-certificates: public-cert