externalSecrets:
  chartVersion: "0.14.3"
  values:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets@voyager-prod-489709.iam.gserviceaccount.com
    nodeSelector:
      role: tools
    tolerations:
      - key: role
        value: tools
        effect: NoSchedule
    webhook:
      nodeSelector:
        role: tools
      tolerations:
        - key: role
          value: tools
          effect: NoSchedule
    certController:
      nodeSelector:
        role: tools
      tolerations:
        - key: role
          value: tools
          effect: NoSchedule