apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-env
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  .env: |
    {{- if not .Values.externalSecrets.enabled }}
    POSTGRES_USER={{ .Values.secrets.POSTGRES_USER | default "postgres" }}
    POSTGRES_PASSWORD={{ .Values.secrets.POSTGRES_PASSWORD }}
    POSTGRES_DB={{ .Values.config.POSTGRES_DB | default "postgres" }}
    POSTGRES_SERVER_HOST={{ .Values.config.POSTGRES_SERVER_HOST | default "localhost" }}
    JWT_KEY={{ .Values.secrets.JWT_KEY }}
    {{- else }}
    POSTGRES_USER=placeholder
    POSTGRES_PASSWORD=placeholder
    POSTGRES_DB=placeholder
    POSTGRES_SERVER_HOST=placeholder
    JWT_KEY=placeholder
    {{- end }}
    CLIENT_URL={{ .Values.config.CLIENT_URL }}
    SERVER_PORT={{ .Values.config.SERVER_PORT }}
    RUN_MIGRATION={{ .Values.config.RUN_MIGRATION }}