{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "backend.fullname" . }}-secrets
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.storeName }}
  target:
    name: {{ include "backend.fullname" . }}-secrets
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.dbCredentialsSecret }}
        property: password
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.externalSecrets.dbCredentialsSecret }}
        property: username
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.externalSecrets.dbCredentialsSecret }}
        property: database
    - secretKey: POSTGRES_SERVER_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.dbCredentialsSecret }}
        property: host
    - secretKey: JWT_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.jwtKeySecret }}
{{- end }}