apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: <PROD_PROJECT_ID>
      auth:
        workloadIdentity:
          clusterLocation: <GCP_REGION>
          clusterName: voyager-prod
          clusterProjectID: <PROD_PROJECT_ID>
          serviceAccountRef:
            name: prod-external-secrets
            namespace: external-secrets