apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: voyager-prod-500708
      auth:
        workloadIdentity:
          clusterLocation: europe-north1
          clusterName: voyager-prod
          clusterProjectID: voyager-prod-500708
          serviceAccountRef:
            name: prod-external-secrets
            namespace: external-secrets