apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-exporter-password
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: postgres-exporter-password
  data:
    - secretKey: password
      remoteRef:
        key: voyager-prod-db-credentials
        property: password