apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: external-secrets
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: {{ .Values.externalSecrets.chartVersion }}
    chart: external-secrets
    helm:
      values: |
        {{- .Values.externalSecrets.values | toYaml | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true