apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: loki
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: {{ .Values.loki.chartVersion }}
    chart: loki
    helm:
      values: |
        {{- .Values.loki.values | toYaml | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true